In [35]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as pl

In [ ]:
import numpy as np

In [5]:
movies = pd.read_csv(r"C:\Users\Raj Vishwakarma\Downloads\MovieLens 20M Dataset\movie.csv")

In [6]:
movies.shape

(27278, 3)

In [7]:
movies.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [8]:
movies.head(5)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [9]:
type(movies)

pandas.core.frame.DataFrame

In [10]:
tags = pd.read_csv(r"C:\Users\Raj Vishwakarma\Downloads\MovieLens 20M Dataset\tag.csv")

In [11]:
tags.shape

(465564, 4)

In [12]:
type(tags)

pandas.core.frame.DataFrame

In [13]:
tags.columns

Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [17]:
tags.head(5)

   userId  movieId            tag            timestamp
0      18     4141    Mark Waters  2009-04-24 18:19:40
1      65      208      dark hero  2013-05-10 01:41:18
2      65      353      dark hero  2013-05-10 01:41:19
3      65      521  noir thriller  2013-05-10 01:39:43
4      65      592      dark hero  2013-05-10 01:41:18

In [14]:
ratings = pd.read_csv(r"C:\Users\Raj Vishwakarma\Downloads\MovieLens 20M Dataset\rating.csv")

In [15]:
type(ratings)

pandas.core.frame.DataFrame

In [16]:
ratings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [18]:
ratings.head(5)

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

In [19]:
print(movies.columns)
print(ratings.columns)
print(tags.columns)

Index(['movieId', 'title', 'genres'], dtype='object')
Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')
Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

In [20]:
del ratings['timestamp']

In [21]:
print(ratings.columns)

Index(['userId', 'movieId', 'rating'], dtype='object')

In [23]:
ratings.describe()

             userId       movieId        rating
count  2.000026e+07  2.000026e+07  2.000026e+07
mean   6.904587e+04  9.041567e+03  3.525529e+00
std    4.003863e+04  1.978948e+04  1.051989e+00
min    1.000000e+00  1.000000e+00  5.000000e-01
25%    3.439500e+04  9.020000e+02  3.000000e+00
50%    6.914100e+04  2.167000e+03  3.500000e+00
75%    1.036370e+05  4.770000e+03  4.000000e+00
max    1.384930e+05  1.312620e+05  5.000000e+00

In [24]:
ratings.mean()

userId     69045.872583
movieId     9041.567330
rating         3.525529
dtype: float64

In [25]:
ratings.min()

userId     1.0
movieId    1.0
rating     0.5
dtype: float64

In [26]:
ratings.max()

userId     138493.0
movieId    131262.0
rating          5.0
dtype: float64

In [28]:
ratings.corr()

           userId   movieId    rating
userId   1.000000 -0.000850  0.001175
movieId -0.000850  1.000000  0.002606
rating   0.001175  0.002606  1.000000

In [29]:
ratings.std()

userId     40038.626653
movieId    19789.477445
rating         1.051989
dtype: float64

In [30]:
print(ratings['rating']>10)

0           False
1           False
2           False
3           False
4           False
            ...
20000258    False
20000259    False
20000260    False
20000261    False
20000262    False
Name: rating, Length: 20000263, dtype: bool

In [31]:
print(movies.isnull())
print(ratings.isnull())
print(tags.isnull())

       movieId  title  genres
0        False  False   False
1        False  False   False
2        False  False   False
3        False  False   False
4        False  False   False
...        ...    ...     ...
27273    False  False   False
27274    False  False   False
27275    False  False   False
27276    False  False   False
27277    False  False   False

[27278 rows x 3 columns]
          userId  movieId  rating
0          False    False   False
1          False    False   False
2          False    False   False
3          False    False   False
4          False    False   False
...          ...      ...     ...
20000258   False    False   False
20000259   False    False   False
20000260   False    False   False
20000261   False    False   False
20000262   False    False   False

[20000263 rows x 3 columns]
        userId  movieId    tag  timestamp
0        False    False  False      False
1        False    False  False      False
2        False    False  False      False
3        False    False  False      False
4        False    False  False      False
...        ...      ...    ...        ...
465559   False    False  False      False
465560   False    False  False      False
465561   False    False  False      False
465562   False    False  False      False
465563   False    False  False      False

[465564 rows x 4 columns]